# Generated by Django 5.2.7 on 2025-11-07 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_resultadovalidacionia_detalles_analisis'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bitacora',
        ),
    ]
