# Generated by Django 5.2.6 on 2025-11-22 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_bitacora'),
        ('api', '0009_plancuota_estado_plancuota_fecha_pago_and_more'),
    ]

    operations = [
    ]
