# Generated by Django 5.2.6 on 2025-11-24 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_merge_20251122_0818'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planpago',
            name='solicitud',
            field=models.OneToOneField(db_column='solicitud_id', on_delete=django.db.models.deletion.CASCADE, related_name='plan', to='api.solicitudcredito'),
        ),
        migrations.CreateModel(
            name='ConfiguracionReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voz_activa', models.BooleanField(default=False)),
                ('tipo_voz', models.CharField(default='es-ES-Standard-A', max_length=50)),
                ('velocidad_voz', models.IntegerField(default=1)),
                ('formato_predeterminado', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('texto', 'Texto')], default='pdf', max_length=10)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_reporte', models.CharField(choices=[('creditos', 'Reporte de Créditos'), ('clientes', 'Reporte de Clientes'), ('pagos', 'Reporte de Pagos'), ('riesgo', 'Reporte de Riesgo')], max_length=20)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('texto', 'Texto')], max_length=10)),
                ('filtros', models.JSONField(default=dict)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='reportes/')),
                ('contenido_texto', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
